name: "Build chocofi nice_nano nice_view"
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano//zmk"]'
      shield: '["corne_left nice_view_adapter nice_view","corne_right nice_view_adapter nice_view"]'
      alphas: '["QWERTY"]'
      nav: '["vi"]'
      layers: '["default"]'
      mapping: '["default"]'
      extra: '["default"]'
      tap: '["default"]'
      clipboard: '["default"]'
      kconfig: '["CONFIG_ZMK_DISPLAY=y"]'
      branches: '["default"]'
